site_name: Megaport ONE Documentation
site_url: https://servicedeployed.github.io/documentation/
nav:
    - Home: index.md
    - Examples: examples
    - Webinars: webinars

plugins:
  - include-markdown